/**
 * Live smoke test for the curated business-type category taxonomy
 * (@/lib/categories/business-type-taxonomy.ts) and its grounding of the
 * AI Assistant's category suggestions (buildConfigTargetSystemPrompt,
 * @/lib/assistant/shared.ts).
 *
 * User-requested directly: "is it possible to have a list of what someone
 * is selling based on business type, since anyone can input anything yet
 * they are of the same niche" (Jiji.co.ke's category browser as the
 * reference point). Confirmed via direct code search that no such list
 * existed anywhere before this — category suggestions were freely
 * generated by Claude per-conversation, so two tenants with the identical
 * business type could land on completely different category names for
 * the same real thing.
 *
 * Two parts:
 *  1. Taxonomy data sanity — every business type from register/page.tsx's
 *     own real businessTypes list (except "Other", which has no curated
 *     entry on purpose) has a real, non-empty, deduplicated category list.
 *  2. A real Claude call: confirm the AI's suggestedCategoryNames for a
 *     real business type are drawn FROM the curated list (a strict subset
 *     check, not just "sounds similar") and correctly exclude a category
 *     the tenant already has.
 *
 * Usage: npm run test:category-taxonomy
 */

import * as dotenv from 'dotenv';
import { resolve } from 'path';

dotenv.config({ path: resolve(process.cwd(), '.env.local') });

// The exact real business type list from src/app/register/page.tsx —
// kept as a literal copy here (not imported) since that file is a
// 'use client' component; duplicating this one list is simpler and safer
// than restructuring the register page just for a test import.
const REAL_BUSINESS_TYPES = [
  'Fashion & Clothing',
  'Beauty & Personal Care',
  'Electronics & Gadgets',
  'Home & Kitchen',
  'Groceries & Food',
  'Bakery & Cakes',
  'Restaurant & Takeaway',
  'Agriculture & Farm Supplies',
  'Flowers & Gifts',
  'Health & Pharmacy',
  'Automotive & Motorbike',
  'Hardware & Construction',
  'Sports & Outdoor',
  'Toys, Kids & Baby Products',
  'Pets & Animals',
  // 'Other' deliberately excluded — no curated entry exists for it.
];

const TEST_TENANT_ID = 'e401c99b-c078-4ab4-96f9-fc901f9110a9'; // testtwo — real tenant, businessType 'Home & Kitchen'

async function main() {
  if (!process.env.ANTHROPIC_API_KEY) throw new Error('ANTHROPIC_API_KEY is required in .env.local');
  if (!process.env.DATABASE_URL) throw new Error('DATABASE_URL is required in .env.local');

  const { BUSINESS_TYPE_CATEGORIES, getCategoriesForBusinessType } = await import('../src/lib/categories/business-type-taxonomy');
  const { generateJsonFromConversation } = await import('../src/lib/ai/claude-client');
  const { buildConfigTargetSystemPrompt, configTargetSchema } = await import('../src/lib/assistant/shared');
  const { prisma } = await import('../src/lib/prisma/client');

  let passed = 0;
  let total = 0;
  function check(label: string, condition: boolean, detail?: unknown) {
    total++;
    if (condition) {
      passed++;
      console.log(`PASS: ${label}`);
    } else {
      console.log(`FAIL: ${label}`, detail ?? '');
    }
  }

  console.log('--- Part 1: taxonomy data sanity ---');
  for (const businessType of REAL_BUSINESS_TYPES) {
    const categories = getCategoriesForBusinessType(businessType);
    check(`"${businessType}" has a real, non-empty curated list`, categories.length >= 5, categories);
    check(`"${businessType}" has no duplicate names`, new Set(categories).size === categories.length, categories);
  }
  check('"Other" deliberately has no curated entry', getCategoriesForBusinessType('Other').length === 0);
  check('unrecognized business type falls back to empty (never throws)', getCategoriesForBusinessType('Some Made Up Type').length === 0);
  check('null business type falls back to empty', getCategoriesForBusinessType(null).length === 0);
  console.log(`Total real business types covered: ${Object.keys(BUSINESS_TYPE_CATEGORIES).length}`);

  console.log('\n--- Part 2: real Claude call grounds suggestions in the curated list ---');
  const tenant = await prisma.tenants.findUnique({ where: { id: TEST_TENANT_ID }, select: { data: true } });
  if (!tenant) throw new Error('Test tenant not found');
  const tenantData = (tenant.data ?? {}) as Record<string, unknown>;
  const businessType = typeof tenantData.business_type === 'string' ? tenantData.business_type : null;
  console.log(`Real tenant's recorded businessType: "${businessType}"`);
  const curated = getCategoriesForBusinessType(businessType);
  check('real tenant has a recognized business type with a curated list', curated.length > 0, businessType);

  const existingCategories = await prisma.categories.findMany({
    where: { tenant_id: TEST_TENANT_ID, status: 'active' },
    select: { name: true },
  });
  const existingNames = existingCategories.map((c) => c.name);
  console.log(`Real existing categories: ${existingNames.join(', ')}`);

  const { data } = await generateJsonFromConversation<{ target: string; suggestedCategoryNames: string[]; categoryNames: string[] }>({
    system: buildConfigTargetSystemPrompt(businessType, null, existingNames),
    messages: [{ role: 'user', content: 'help me set up a couple more categories for my store' }],
    schema: configTargetSchema,
    maxTokens: 300,
  });

  console.log('Suggested:', data.suggestedCategoryNames);
  check('target resolved to category', data.target === 'category', data.target);
  check('at least one suggestion was made', data.suggestedCategoryNames.length > 0, data.suggestedCategoryNames);
  const allFromCuratedList = data.suggestedCategoryNames.every((name) => curated.includes(name));
  check('every suggested name is drawn from the real curated list (not invented)', allFromCuratedList, {
    suggested: data.suggestedCategoryNames,
    curated,
  });
  const noDuplicatesOfExisting = data.suggestedCategoryNames.every((name) => !existingNames.includes(name));
  check('no suggestion duplicates a category the tenant already has', noDuplicatesOfExisting, {
    suggested: data.suggestedCategoryNames,
    existing: existingNames,
  });

  console.log(`\n${passed}/${total} checks passed.`);
  await prisma.$disconnect();
  if (passed !== total) process.exit(1);
}

main().catch((error) => {
  console.error('\nCategory taxonomy test failed:', error);
  process.exit(1);
});
